name = "tabi"
description = "A fast, lightweight, and modern Zola theme with multi-language support, optional JavaScript, and a perfect Lighthouse score"
license = "MIT"
homepage = "https://github.com/welpo/tabi"

# The minimum version of Zola required
min_version = "0.9.0"

# An optional live demo URL
demo = "https://welpo.github.io/tabi"

# The theme author info: you!
[author]
name = "Óscar Fernández"
homepage = "https://osc.garden"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# Languages of your site.
# You'll need to add the language translations for each non-English language.
# See the config.toml file for an example.
language_name.ca = "Català"
language_name.en = "English"
language_name.es = "Español"

# Enable JavaScript theme toggler for dark/light mode (and automatic switching).
# The default setting is the light theme.
theme_switcher = true

# Date format used when listing posts (main page, /blog section, tag posts list…)
# Default is "6th July 2049".
long_date_format = "%d %B %Y"

separator = "•"

# Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = ""

# Add an emoji here to use it as favicon.
# Compatibility: https://caniuse.com/link-icon-svg
favicon_emoji = "🌱"

menu = [
    { name = "blog", url = "$BASE_URL/blog" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "projects", url = "$BASE_URL/projects" },
]

# Custom security headers. What urls should your website be able to connect to?
# You need to specify the CSP and the URLs associated with the directive.
# Useful if you want to load remote content safely (embed YouTube videos, which needs frame-src, for example).
# Default directive is self.
# Default config, allows for https remote images and embedding YouTube and Vimeo content.
# This configuration (along with the right webserver settings) gets an A+ in Mozilla's Observatory: https://observatory.mozilla.org
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

# Custom subset of characters for the header.
# If set to true, the `static/custom_subset.css` file will be loaded first.
# This avoids a flashing text issue in Firefox.
# Please see https://welpo.github.io/tabi/blog/custom-font-subset/ to learn how to create this file.
custom_subset = true
